services:
  shell:
    build:
      context: .
      dockerfile: Dockerfile
    image: "croco-mecab:latest"
    working_dir: "/home/croco/mecab"
    environment:
      - "LANG=ja_JP.UTF-8"
      - "LANGUAGE=ja"
    volumes:
      - $PWD/src:/home/croco/mecab
    tty: true

