services:
  shell:
    build:
      context: .
      dockerfile: Dockerfile
    image: "croco-embedding:latest"
    working_dir: "/home/croco/embedding"
    environment:
      - "LANG=ja_JP.UTF-8"
      - "LANGUAGE=ja"
    volumes:
      - $PWD/src:/home/croco/embedding
      - /models:/models
    tty: true

